ENG-612: Token Studio backend support: return details from synchronizeTokensFromData
Supernova-Studio/sdk-typescript pull request #31
Opened 2023-01-17 17:57 UTC by tchief

### Changes
- Added `synchronizeTokensFromDataWithResults` method that returns imported results data from `mergeWithRemoteSource`.
  - Existing `synchronizeTokensFromData` should not be changed.
  - Keep `stop on first failure` behavior.
- Added `SupernovaToolsDesignTokensResult` as container for result data
- Export few related types
- Bump version

2023-01-17 17:58 UTC, tchief commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +export type SupernovaToolsDesignTokensResult = {
Another option is to not return tokens, but use slimmer type, like this
```
export type SupernovaToolsDesignTokensResultSlim = {
    map: DTPluginToSupernovaMap
    tokensCreated: number;
    tokensUpdated: number;
    tokensDeleted: number;
  }
```
and fill it like this
```
  results.push({
    map, 
    tokensCreated: mergeResult.diff.toCreate.length,
    tokensUpdated: mergeResult.diff.toUpdate.length,
    tokensDeleted: mergeResult.diff.toDelete.length
  });
  // ...
  results.push({
    map, 
    tokensCreated: 0,
    tokensUpdated: mergeResult.tokens.length,
    tokensDeleted: 0
  });
```

2023-01-17 17:59 UTC, tchief commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +  map: DTPluginToSupernovaMap
Another option to remove nodes properties from `DTPluginToSupernovaMap`
```
Omit<DTPluginToSupernovaMap, "nodes" | "processedNodes" | "processedGroups">
```

2023-01-17 18:00 UTC, tchief commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +      tokens: themeMergerResult.overriddenTokens
Would `theme.overridenTokens` contain same data as `themeMergerResult.overriddenTokens`? If so, I can remove this new property and get everything from `theme`.

2023-01-17 18:00 UTC, tchief commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +  async synchronizeTokensFromDataWithResults(
Created separate method, not sure whether this one is used by external clients. Could leave just one method if that's better.

2023-01-18 08:11 UTC, tchief commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +  map: DTPluginToSupernovaMap
We also might send less data in this case (exclude `nodes`)

2023-01-18 15:11 UTC, JiriTrecak requested changes
Left few comments, thank you!

2023-01-18 15:11 UTC, JiriTrecak commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +export type SupernovaToolsDesignTokensResult = {
I think we should do a middle ground - use your slim maps, but instead of `number`, use tokens.map(t => t.id) from SDK. This way we can also reference tokens that were created/deleted etc. - WDYT?

I think there is value in keeping the reference to what was what.

2023-01-18 15:11 UTC, JiriTrecak commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +export type SupernovaToolsDesignTokensResult = {
+ of course don't call it slim :)

2023-01-18 15:11 UTC, JiriTrecak commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +  map: DTPluginToSupernovaMap
I agree, raw data are not at all useful for the result

2023-01-18 15:11 UTC, JiriTrecak commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +  async synchronizeTokensFromDataWithResults(
@tchief I would only keep the method that handles the data, and completely remove methods that handle loading from file and loading from directory. The reason being that I want to remove `fs` package from the dependencies so SDK can be used in the browser - then, we can move the `fs` handling to the CLI to pre-process the data for the user and use the same routines that were used here (I'll do that part). For consumer, nothing will change because they are not using SDK directly, only through CLI.

So basically, here:
https://github.com/Supernova-Studio/cli/blob/main/src/commands/sync-tokens.ts#L86
We'd change to load from data, and move the functions to pre-process the data to the CLI.

2023-01-18 15:11 UTC, JiriTrecak commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +      tokens: themeMergerResult.overriddenTokens
I'd keep the merger result, because it might not be guaranteed going forward this will be the case.

2023-01-19 10:27 UTC, tchief commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +  async synchronizeTokensFromDataWithResults(
@JiriTrecak Maybe we should do this in separate PR, so we can release new SDK so we can deploy API to dev to test, without depending on making CLI changes and releasing it? WDYT?

2023-01-19 10:35 UTC, tchief commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +export type SupernovaToolsDesignTokensResult = {
Is this better?
```
export type SupernovaToolsDesignTokensResult = {
    map: Pick<DTPluginToSupernovaMap, 'bindToBrand' | 'bindToTheme' | 'pluginSets' | 'pluginTheme' | 'type'>
    tokensCreated: Array<string>;
    tokensUpdated: Array<string>;
    tokensDeleted: Array<string>;
  }
```

We could do `id` for now.
I think we would need more data, than just `id` if we want to somehow process tokens later. At this point it's just a speculation, probably we never need it.

2023-01-19 10:39 UTC, tchief commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +        tokensDeleted: []
@JiriTrecak I consider results of `mergeThemeWithRemoteSource` for theme as `tokensUpdated`
```
console.log(`Created or updated overrides: ${themeMergerResult.overriddenTokens.length}`)
```

2023-01-19 10:39 UTC, tchief reviewed
Add comment

2023-01-19 11:09 UTC, tchief commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +export type SupernovaToolsDesignTokensResult = {
The only concern with just ids: on calling API `/token-studio` all we can return are ids in this case.

2023-01-19 14:05 UTC, JiriTrecak commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +  async synchronizeTokensFromDataWithResults(
I agree, let's do it separately

2023-01-19 14:06 UTC, JiriTrecak commented on src/tools/design-tokens/SDKToolsDesignTokensPlugin.ts
> +export type SupernovaToolsDesignTokensResult = {
I think that is fine. Don't expect it to be used nonetheless, not for now, and we can always expand on it.

2023-01-19 14:08 UTC, JiriTrecak approved these changes

2023-01-19 14:09 UTC, merged